version: "0.1"

pipeline:
  # Pipeline variables
  - vars:
      llm_threshold_amount: 2000
      high_risk_debt_ratio: 0.5
      min_credit_score: 300
      
  # Schema validation
  - type: validate
    id: input_validation
    schema: LoanApplicationSchema
    on_error:
      action: fail
      return_error: true
      
  # Extract applicant profile with enrichment
  - type: extract
    id: extract_applicant_profile
    
  - type: enrich
    id: credit_bureau_data
    source: external_api
    endpoint: /api/credit-check
    cache:
      enabled: true
      ttl: 86400  # 24 hours
    on_error:
      action: fallback
      fallback:
        credit_score: 500
        
  # Extract income sources
  - type: extract
    id: extract_income_sources
    
  # Conditional LLM reasoning for high-value applications
  - type: reason
    id: applicant_llm_reasoning
    if: "event.applicant.request_amount > vars.llm_threshold_amount"
    
    provider: openai
    model: gpt-4-turbo
    
    prompt:
      template: |
        Analyze this loan application for risk:
        
        Applicant:
        - Income: ${event.applicant.income}
        - Requested Amount: ${event.applicant.request_amount}
        - Employment Type: {event.applicant.employment_type}
        - Credit Score: {context.credit_bureau_data.credit_score}
        
        Assess employment stability and repayment capacity.
        
    output_schema:
      employment_stability: float
      repayment_capacity: float
      risk_factors: array<string>
      
    config:
      temperature: 0.3
      max_tokens: 500
      timeout: 5000
      
    cache:
      enabled: true
      ttl: 3600
      key: "loan_analysis:{event.applicant.id}:{event.applicant.request_amount}"
      
    on_error:
      action: fallback
      fallback:
        employment_stability: 0.5
        repayment_capacity: 0.5
        risk_factors: ["llm_unavailable"]
        
  # Include loan credit rules
  - include:
      ruleset: loan_credit_rules
      
  # Weighted aggregation with dynamic weights
  - aggregate:
      method: weighted
      weights:
        context.loan_credit_rules.score: 0.5
        context.applicant_llm_reasoning.risk_score: |
          event.applicant.request_amount > 10000 ? 0.5 : 0.3
      output: context.final_risk_score
      
  # Final decision with comprehensive logging
  - type: action
    id: final_decision
    observability:
      log:
        level: info
        include:
          - action
          - score
          - llm_reasoning
          - credit_score
      audit:
        enabled: true
        retention_days: 2555  # 7 years for financial records
      metric:
        name: loan_decisions_total
        type: counter
        labels:
          action: context.final_decision.action
          loan_amount_bucket: bucket(event.applicant.request_amount, [1000, 5000, 10000, 50000])