version: "0.1"

pipeline:
  # Define pipeline variables
  - vars:
      risk_threshold: 80
      max_failed_attempts: 5
      high_risk_countries: ["RU", "NG", "UA", "CN"]
      
  # Validate input
  - type: validate
    id: input_validation
    schema: LoginEventSchema
    on_error:
      action: fail
      
  # Extract features
  - type: extract
    id: extract_device
    cache:
      enabled: true
      ttl: 3600
      key: "device:{event.device.id}"

  - type: extract
    id: extract_ip
    
  # Parallel intelligence checks with caching
  - parallel:
      - type: api
        id: device_fingerprint
        cache:
          enabled: true
          ttl: 1800
        on_error:
          action: fallback
          fallback:
            trust_score: 0.5
            
      - type: api
        id: ip_reputation
        cache:
          enabled: true
          ttl: 3600
        timeout: 2000
        retry:
          max_attempts: 2
          backoff: exponential
          
      - type: reason
        id: llm_reasoning
        provider: openai
        model: gpt-4-turbo
        cache:
          enabled: true
          ttl: 1800
        on_error:
          action: skip
          
    merge:
      method: all
      
  # Include login risk rules
  - include:
      ruleset: login_risk_rules
      
  # Aggregate scores with context
  - aggregate:
      method: weighted
      weights:
        context.login_risk_rules.score: 0.6
        context.llm_reasoning.risk_score: 0.3
        context.ip_reputation.score: 0.1
      output: context.final_risk_score
      
  # Final action with observability
  - type: action
    id: final_decision
    observability:
      log:
        level: info
        include: [action, score, triggered_rules]
      audit:
        enabled: true
      metric:
        name: login_decisions_total
        type: counter
        labels:
          action: context.final_decision.action
          country: event.geo.country
