version: "0.1"

pipeline:
  # Variables
  - vars:
      velocity_threshold: 10
      high_value_amount: 10000
      
  # Extract payment features with precomputed data
  - type: extract
    id: extract_payment_base
    precomputed:
      enabled: true
      source: redis
      features:
        - user_transaction_count_24h
        - user_avg_amount_30d
        
  # Parallel checks with error handling
  - parallel:
      - type: custom
        id: velocity_check
        cache:
          enabled: true
          ttl: 300
        on_error:
          action: fallback
          fallback:
            velocity_score: 50
            
      - type: api
        id: beneficiary_reputation
        timeout: 3000
        retry:
          max_attempts: 2
        on_error:
          action: fallback
          fallback:
            reputation_score: 50
            
      - type: reason
        id: llm_payment_semantics
        if: "event.transaction.amount > vars.high_value_amount"
        provider: openai
        model: gpt-4-turbo
        config:
          temperature: 0.3
          max_tokens: 500
          timeout: 5000
        cache:
          enabled: true
          ttl: 1800
        on_error:
          action: skip
          
    merge:
      method: all
      on_partial_data:
        action: continue
        min_required: 2
        
  # Include payment risk rules
  - include:
      ruleset: payment_risk_rules
      
  # Aggregate with reweighting on partial data
  - aggregate:
      method: sum
      sources:
        - context.velocity_check.score
        - context.beneficiary_reputation.score
        - context.llm_payment_semantics.risk_score
      reweight: true
      output: context.total_risk_score
      
  # Final action with metrics
  - type: action
    id: final_decision
    observability:
      log:
        level: info
        sampling_rate: 0.1
      metric:
        name: payment_decisions_total
        type: counter
        labels:
          action: context.final_decision.action
          amount_bucket: bucket(event.transaction.amount, [100, 1000, 10000])
