version: "0.1"

pipeline:
  # Variables
  - vars:
      chainalysis_threshold: 80
      min_wallet_age_days: 30
      
  # Extract wallet information
  - type: extract
    id: extract_web3_wallet
    
  # Chainalysis blockchain intelligence
  - type: api
    id: chainalysis_lookup
    provider: chainalysis
    endpoint: /api/v1/address/{event.wallet.address}
    
    # Cache blockchain data (immutable for most practical purposes)
    cache:
      enabled: true
      ttl: 7200  # 2 hours
      key: "chainalysis:{event.wallet.address}"
      
    # Timeout and retry for external service
    timeout: 5000
    retry:
      max_attempts: 3
      backoff: exponential
      initial_delay: 1000
      
    # Circuit breaker for service protection
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      open_timeout: 60000
      
    on_error:
      action: fallback
      fallback:
        risk_score: 50
        risk_category: "unknown"
        
  # LLM wallet behavior analysis
  - type: reason
    id: llm_wallet_analysis
    
    provider: openai
    model: gpt-4-turbo
    
    prompt:
      template: |
        Analyze this cryptocurrency wallet for risk:
        
        Wallet: {event.wallet.address}
        Blockchain: {event.wallet.blockchain}
        Balance: {event.wallet.balance}
        Transaction Count: {event.wallet.tx_count}
        Age (days): {event.wallet.age_days}
        
        Chainalysis Risk Score: {context.chainalysis_lookup.risk_score}
        Chainalysis Category: {context.chainalysis_lookup.risk_category}
        
        Assess the wallet's legitimacy and usage patterns.
        
    output_schema:
      legitimacy_score: float
      usage_pattern: string
      red_flags: array<string>
      confidence: float
      
    config:
      temperature: 0.3
      max_tokens: 600
      
    cache:
      enabled: true
      ttl: 3600
      key: "wallet_analysis:{event.wallet.address}:{sys.date}"
      
    on_error:
      action: skip
      log_level: warn
      
  # Include Web3-specific risk rules
  - include:
      ruleset: web3_wallet_risk
      
  # Use max score (most conservative for crypto)
  - aggregate:
      method: max
      sources:
        - context.chainalysis_lookup.risk_score
        - context.llm_wallet_analysis.legitimacy_score
        - context.web3_wallet_risk.score
      output: context.max_risk_score
      
  # Final decision with Web3-specific metrics
  - type: action
    id: final_decision
    observability:
      log:
        level: info
        include:
          - wallet_address: event.wallet.address
          - blockchain: event.wallet.blockchain
          - chainalysis_score: context.chainalysis_lookup.risk_score
          - decision: context.final_decision.action
      audit:
        enabled: true
        retention_days: 2555  # Regulatory requirement
      metric:
        - name: web3_decisions_total
          type: counter
          labels:
            action: context.final_decision.action
            blockchain: event.wallet.blockchain
            risk_category: context.chainalysis_lookup.risk_category
            
        - name: web3_risk_scores
          type: histogram
          value: context.max_risk_score
          buckets: [20, 40, 60, 80, 100]
